import type { Metadata } from 'next'
import { Roboto, Nunito } from 'next/font/google'
import './globals.css'
import Navbar from './shared-components/Navbar'

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
})

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${nunito.variable} ${nunito.variable} antialiased dark:bg-black dark:text-white`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    )
}
