name: Build and Test App

on:
  push:
    branches: [ 'feature/**' ]
  pull_request:
    branches: [ 'copilot/**' ]

jobs:
  build:
    name: Build Application
    uses: ./.github/workflows/build.yml
    secrets: # Passing in is required to set environment secrets correctly but not variables.
      ACCESS_KEY_ID_AWS: ${{ secrets.ACCESS_KEY_ID_AWS }}
      SECRET_ACCESS_KEY_AWS: ${{ secrets.SECRET_ACCESS_KEY_AWS }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

  functional-tests:
    needs: build
    name: Run Playwright Tests
    uses: ./.github/workflows/playwright-test.yml
    with:
      ENVIRONMENT: test
      PLAYWRIGHT_PROJECT: e2e-all-browsers
    secrets: # Passing in is required to set environment secrets correctly but not variables.
      ACCESS_KEY_ID_AWS: ${{ secrets.ACCESS_KEY_ID_AWS }}
      SECRET_ACCESS_KEY_AWS: ${{ secrets.SECRET_ACCESS_KEY_AWS }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
