name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  functional-tests:
    needs: build
    uses: ./.github/workflows/playwright-test.yml
    secrets: inherit
