name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
     secrets:
      ACCESS_KEY_ID_AWS: ${{ secrets.ACCESS_KEY_ID_AWS }}
      SECRET_ACCESS_KEY_AWS: ${{ secrets.SECRET_ACCESS_KEY_AWS }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

  functional-tests:
    needs: build
    uses: ./.github/workflows/playwright-test.yml
    secrets: inherit
