name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Application
    uses: ./.github/workflows/build.yml
    secrets: inherit

  functional-tests:
    needs: build
    name: Run Playwright Tests
    uses: ./.github/workflows/playwright-test.yml
    secrets: inherit