name: Smoke Test Live App

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
        default: production
jobs:
  functional-tests:
    needs: build
    name: Run Playwright Tests
    uses: ./.github/workflows/playwright-test.yml
    with:
      ENVIRONMENT: inputs.ENVIRONMENT
      PLAYWRIGHT_PROJECT: smoke-test