name: Smoke Test Live App

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
        default: prod
jobs:
  smoke-tests:
    name: Run Playwright Tests
    uses: ./.github/workflows/playwright-test.yml
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      PLAYWRIGHT_PROJECT: smoke-test